# Generated by Django 3.2.5 on 2021-07-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email already exist'}, max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.TextField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
            ],
        ),
    ]
